### ISSUE TITLE
问下frpc使用range来配置代理端口,会有性能问题吗

### ISSUE THREAD

**Issue by 643104191** [stilleshan/frpc#12]
如题,极限情况下,配置一个1-65535的range,会不会炸机

**Comment by stilleshan** [comment]
这得看服务器性能吧。

**Comment by 643104191** [comment]
> 这得看服务器性能吧。

那意思就是会影响性能的咯?我看有些地方,说range里有多少个端口就会创建多少个proxy,
创建的proxy多了,应该是会影响的吧

**Comment by stilleshan** [comment]
这个建议你到官方项目提 issue 咨询下。
https://github.com/fatedier/frp

**Comment by 643104191** [comment]
> 这个建议你到官方项目提 issue 咨询下。 https://github.com/fatedier/frp

好的,多谢
