### ISSUE TITLE
frp为什么使用的是我内网的上传带宽

### ISSUE THREAD

**Issue by tanglei0809** [stilleshan/frpc#18]
请教下大佬,我使用公网服务器将我内网的nas穿透出去,但是nas上显示是使用的我内网的上传带宽,请问大佬怎么能改成使用下载的带宽

**Comment by stilleshan** [comment]
这不就是应该的么？ 外面访问你家里NAS，你家NAS肯定是上传数据出去啊。

**Comment by tanglei0809** [comment]
😂😂请问下如果frp 设置点对点 是不是就是使用的下行带宽了，然后如果有公网直连是不是下行发自我的 iPhone在 2024年2月4日，09:13，Stille ***@***.***> 写道：﻿
这不就是应该的么？ 外面访问你家里NAS，你家NAS肯定是上传数据出去啊。
