### ISSUE TITLE
dokcer版本能否考虑加一个web管理

### ISSUE THREAD

**Issue by q123458384** [stilleshan/frpc#2]
dokcer版本能否考虑加一个web管理，
之前有用过N1小钢炮的frpc，有web管理界面，修改可以试试生效。
目前用的你这个配置修改了必须重启容器才能生效会麻烦一点

**Comment by stilleshan** [comment]
没有合适的,暂不考虑.

**Comment by q123458384** [comment]
> 没有合适的,暂不考虑.

或者有什么办法实现 修改配置不需要重启重启生效？
