### ISSUE TITLE
 国内线路超时

### ISSUE THREAD

**Issue by xinxingi** [stilleshan/frpc#28]
国内线路超时

wget https://ghp.ci/https://raw.githubusercontent.com/stilleshan/frpc/master/frpc_linux_install.sh && chmod +x frpc_linux_install.sh && ./frpc_linux_install.sh

![image](https://github.com/user-attachments/assets/5407c5cb-4e79-4f81-96c4-48eece278b0d)

**Comment by stilleshan** [comment]
代理网站访问也会出现网络问题，多尝试下。
