### ISSUE TITLE
添加树莓派的支持

### ISSUE THREAD

**Issue by hbyYoyo** [stilleshan/frpc#5]
能否添加树莓派的支持
armv7l----->32位的arm

**Comment by stilleshan** [comment]
我没有树莓派设备,方便的话联系我,我可以尝试构建给你测试下.你可以在我个人页面找到我的邮箱.

**Comment by hbyYoyo** [comment]
Hi，大佬，新年快乐

关于这个问题，我已经在树莓派4B上做了测试，原因是自动安装脚本中没有包含对应架构的逻辑判断，
导致无法下载对应的Frp功能包。

树莓派4B的系统架构为  armv7l ——> 32 位，不过树莓派系统也有用armv8l ——> 64位，具体位数可
用 getconf LONG_BIT命令查看。

因为大部分架构的Frp包都已经有了（我已经测试了32位arm版本是可行的），因此建议多在脚本中加
几个不同版本的逻辑判断。

最后非常感谢大佬的脚本，真的太好用了😀！

牛逼！
匿名
