### ISSUE TITLE
HTTPS配置提示无法找到证书

### ISSUE THREAD

**Issue by Dev-Wiki** [stilleshan/frpc#8]
使用环境为 威联通的 nas, http 配置正常. 

```
2022/03/13 18:19:11 [W] [control.go:179] [d72a10e8af15e80a] [devwiki_nginx_https] start error: gen TLS config error: open ./ssl/nginx.crt: no such file or directory
2022/03/13 18:19:11 [I] [control.go:181] [d72a10e8af15e80a] [devwiki_git_ssh] start proxy success
2022/03/13 18:19:11 [I] [control.go:181] [d72a10e8af15e80a] [devwiki_nginx] start proxy success
2022/03/13 18:19:11 [I] [control.go:181] [d72a10e8af15e80a] [devwiki_blog] start proxy success
2022/03/13 18:19:11 [I] [control.go:181] [d72a10e8af15e80a] [devwiki_nas] start proxy success
2022/03/13 18:19:11 [W] [control.go:179] [d72a10e8af15e80a] [devwiki_nas_https] start error: gen TLS config error: open ./ssl/nas.crt: no such file or directory
2022/03/13 18:19:11 [I] [control.go:181] [d72a10e8af15e80a] [devwiki_git] start proxy success
```

nas中 配置挂载点:
![image](https://user-images.githubusercontent.com/12946956/158055069-16cfbb68-c0ec-4666-b1b5-1db2dda0c098.png)

不提示找不到 key, 提示找不到 crt, **尝试了直接放在 frp 根目录 也是不行.** 

![image](https://user-images.githubusercontent.com/12946956/158055171-5ecbd0aa-df22-4440-a18b-72dba03bfdd4.png)

配置https 证书, 提示无法找到文件, 使用windows系统测试 证书都正常.
```
C:\GreenSoft\frp_0.39.1_windows_386>frpc.exe -c frpc.ini
2022/03/13 18:19:36 [I] [service.go:327] [b8a1dae036e6c52c] login to server success, get run id [b8a1dae036e6c52c], server udp port [0]
2022/03/13 18:19:36 [I] [proxy_manager.go:144] [b8a1dae036e6c52c] proxy added: [devwiki_nas devwiki_nas_https]
2022/03/13 18:19:36 [I] [service.go:135] admin server listen on 127.0.0.1:7400
2022/03/13 18:19:36 [I] [control.go:181] [b8a1dae036e6c52c] [devwiki_nas] start proxy success
2022/03/13 18:19:36 [I] [control.go:181] [b8a1dae036e6c52c] [devwiki_nas_https] start proxy success
```

**Comment by Dev-Wiki** [comment]
威联通的系统可以在线体验
QNAP 在线体验 | QNAP
https://www.qnap.com.cn/zh-cn/live-demo

**Comment by stilleshan** [comment]
贴frpc.ini 和容器配置

**Comment by Dev-Wiki** [comment]
```ini
[common]
server_addr = xxx
server_port = xxx
token= xxx

# Admin UI 
admin_addr = 127.0.0.1
admin_port = xxx
admin_user = xxx
admin_pwd = xxx

# TCP 多路复用 
tcp_mux = false

# 连接池上限
max_pool_count = 1

[devwiki_nas]
type = http
local_ip=127.0.0.1
local_port=80
custom_domains = nas.devwiki.net

[devwiki_nas_https]
type = https
custom_domains = nas.devwiki.net
plugin = https2http
plugin_local_addr = 127.0.0.1:80
# HTTPS 证书相关的配置
plugin_crt_path = ./ssl/nas.crt
plugin_key_path = ./ssl/nas.key
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp
```

配置, 容器配置 http 正常

![image](https://user-images.githubusercontent.com/12946956/158064029-5c2a7aba-08b8-4dd2-9bf6-d9f02a878217.png)

![image](https://user-images.githubusercontent.com/12946956/158064044-10708463-6270-4608-aaaa-87fd396547c9.png)

**Comment by Dev-Wiki** [comment]
> ```ini
> [common]
> server_addr = xxx
> server_port = xxx
> token= xxx
> 
> # Admin UI 
> admin_addr = 127.0.0.1
> admin_port = xxx
> admin_user = xxx
> admin_pwd = xxx
> 
> # TCP 多路复用 
> tcp_mux = false
> 
> # 连接池上限
> max_pool_count = 1
> 
> [devwiki_nas]
> type = http
> local_ip=127.0.0.1
> local_port=80
> custom_domains = nas.devwiki.net
> 
> [devwiki_nas_https]
> type = https
> custom_domains = nas.devwiki.net
> plugin = https2http
> plugin_local_addr = 127.0.0.1:80
> # HTTPS 证书相关的配置
> plugin_crt_path = ./ssl/nas.crt
> plugin_key_path = ./ssl/nas.key
> plugin_host_header_rewrite = 127.0.0.1
> plugin_header_X-From-Where = frp
> ```
> 
> 配置, 容器配置 http 正常
> 
> ![image](https://user-images.githubusercontent.com/12946956/158064029-5c2a7aba-08b8-4dd2-9bf6-d9f02a878217.png)
> 
> ![image](https://user-images.githubusercontent.com/12946956/158064044-10708463-6270-4608-aaaa-87fd396547c9.png)

本地使用 windows系统按照上述配置是可以的, https 也正常

**Comment by stilleshan** [comment]
把证书挂在到容器里,在把 plugin_crt_path 和 plugin_key_path 的路径改为容器内的路径.

**Comment by Dev-Wiki** [comment]
> 把证书挂在到容器里,在把 plugin_crt_path 和 plugin_key_path 的路径改为容器内的路径.

我试试

**Comment by Dev-Wiki** [comment]
> 把证书挂在到容器里,在把 plugin_crt_path 和 plugin_key_path 的路径改为容器内的路径.

增加 这两个路径 映射到 文件路径里面么?

**Comment by Dev-Wiki** [comment]
> 

威联通的这个容器自己是没有存储路径的, 是需要映射本地的文件夹路径. 比如
 nas盘的: `/share/Container/container-station-data/application/frp`, 对应为 frpc 的 `/frpc` 文件夹

**Comment by stilleshan** [comment]
那路径就是 /frp/ssl/nas.crt

**Comment by Dev-Wiki** [comment]
> 那路径就是 /frp/ssl/nas.crt

对对, 我就改成这样了, 可以了 谢谢, 我整理下, 使用你的镜像, 我写个教程文章

**Comment by Dev-Wiki** [comment]
这个可以关闭了

**Comment by Dev-Wiki** [comment]
这个可以关闭了
